config/routes.rb
require_relative '../bin/include'

ROUTER = Router.new
ROUTER.draw do
  get     Regexp.new("^/$"),                DogsController, :index
  get     Regexp.new("^/dogs$"),            DogsController, :index
  get     Regexp.new("^/dogs/new$"),        DogsController, :new
  post    Regexp.new("^/dogs$"),            DogsController, :create
  get     Regexp.new("^/dogs/(?<id>\\d+)/edit$"), DogsController, :edit
  put     Regexp.new("^/dogs/(?<id>\\d+)$"),      DogsController, :update
  patch   Regexp.new("^/dogs/(?<id>\\d+)$"),      DogsController, :update
  get     Regexp.new("^/dogs/(?<id>\\d+)$"),      DogsController, :show
  delete  Regexp.new("^/dogs/(?<id>\\d+)$"),      DogsController, :destroy
  
  get     Regexp.new("^/humans/(?<id>\\d+)$"),      HumansController, :show
  get     Regexp.new("^/houses/(?<id>\\d+)$"),      HousesController, :show

  # Route for assets
  get Regexp.new("^/assets/(?<folder>[a-zA-Z\/]+)/(?<asset_name>\\w+)\.(?<extension>css|jsx|scss|js)$"), AssetsController, :show
end

app/models/dog.rb
class Dog < ActiveRecordBase
  validates :name, presence: true
  validates :name, length: { minimum: 1 }

  belongs_to :human
  has_one_through :house, :human, :house
end

app/models/house.rb
# require_relative './human.rb'
class House < ActiveRecordBase
  validates :name, presence: true
  validates :name, length: { minimum: 1 }
  
  has_many :humans, {foreign_key: :house_id}
  has_many_through :dogs, :humans, :dogs
end

app/models/human.rb
class Human < ActiveRecordBase
  self.table_name = "humans"
  validates :name, presence: true
  validates :name, length: { minimum: 1 }

  belongs_to :house
  has_many :dogs
end

app/controllers/assets_controller.rb
require 'byebug'
class AssetsController < ControllerBase
  def show
    render_asset(params)
  end
end

app/controllers/dogs_controller.rb
require 'byebug'
class DogsController < ControllerBase
  protect_from_forgery

  def new
    @dog = Dog.new
    @humans = Human.all
    render :new
  end

  def create
    @dog = Dog.new(params[:dog])
    
    if @dog.save
      flash[:success] = "Successfully created a new dog"
      redirect_to("/dogs")
    else
      flash.now[:danger] = "Dog could not be saved"
      @humans = Human.all
      render :new
    end
  end

  def edit
    @dog = Dog.find(params[:id])
    @humans = Human.all
    render :edit
  end

  def update
    @dog = Dog.find(params[:id])

    if @dog.update(params[:dog])
      flash[:success] = "Successfully updated a dog"
      redirect_to("/dogs/#{@dog.id}")
    else
      flash.now[:danger] = "Dog could not be updated"
      render :edit
    end
  end

  def show
    @dog = Dog.find(params[:id])
    render :show
  end

  def index
    @dogs = Dog.all
    render :index
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to("/dogs")
  end
end

app/controllers/houses_controller.rb
class HousesController < ControllerBase
  protect_from_forgery

  # def new
  #   @dog = Dog.new
  #   render :new
  # end

  # def create
  #   @dog = Dog.new(params[:dog])

  #   if @dog.save
  #     flash[:success] = "Successfully created a new dog"
  #     redirect_to("/dogs")
  #   else
  #     flash.now[:danger] = "Dog could not be saved"
  #     render :new
  #   end
  # end

  # def edit
  #   @dog = Dog.find(params[:id])
  #   render :edit
  # end

  # def update
  #   @dog = Dog.find(params[:id])

  #   if @dog.update(params[:dog])
  #     flash[:success] = "Successfully updated a dog"
  #     redirect_to("/dogs/#{@dog.id}")
  #   else
  #     flash.now[:danger] = "Dog could not be updated"
  #     render :edit
  #   end
  # end

  def show
    @house = House.find(params[:id])
    render :show
  end

  # def index
  #   @dogs = Dog.all
  #   render :index
  # end

  # def destroy
  #   @dog = Dog.find(params[:id])
  #   @dog.destroy
  #   redirect_to("/dogs")
  # end
end

app/controllers/humans_controller.rb
class HumansController < ControllerBase
  protect_from_forgery

  # def new
  #   @dog = Dog.new
  #   render :new
  # end

  # def create
  #   @dog = Dog.new(params[:dog])

  #   if @dog.save
  #     flash[:success] = "Successfully created a new dog"
  #     redirect_to("/dogs")
  #   else
  #     flash.now[:danger] = "Dog could not be saved"
  #     render :new
  #   end
  # end

  # def edit
  #   @dog = Dog.find(params[:id])
  #   render :edit
  # end

  # def update
  #   @dog = Dog.find(params[:id])

  #   if @dog.update(params[:dog])
  #     flash[:success] = "Successfully updated a dog"
  #     redirect_to("/dogs/#{@dog.id}")
  #   else
  #     flash.now[:danger] = "Dog could not be updated"
  #     render :edit
  #   end
  # end

  def show
    @human = Human.find(params[:id])
    render :show
  end

  # def index
  #   @dogs = Dog.all
  #   render :index
  # end

  # def destroy
  #   @dog = Dog.find(params[:id])
  #   @dog.destroy
  #   redirect_to("/dogs")
  # end
end

app/views/dogs/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Dog | DOG APP</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster|Pacifico|Cookie|Comfortaa|Ubuntu|Varela+Round">
  <%= AssetPipeline.pipeline %>
</head>
<body>
  <div class="container">
    <ul>
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <%= message %><br>
        </div>
      <% end %>
    </ul>

    <h1>Edit <%= @dog.name %></h1>
    <form action="/dogs/<%= @dog.id %>" method="POST">
      <input type="hidden" name="_method" value='PATCH'>

      <input type="hidden"
             name="authenticity_token"
             value="<%= form_authenticity_token %>">

      <label>Name<br>
        <input class="form-control"
               type="text" name="dog[name]" value="<%= @dog.name %>">
      </label><br>

      <br>
      <label>Human Friend<br>
        <select name="dog[human_id]" class="form-control">
          <option value="0" <%= "selected='selected'" unless @dog.human %>>
            None
          </option>
          <% @humans.each do |human|%>
            <option value="<%= human.id %>"
              <%= "selected='selected'" if @dog &&  @dog.human && @dog.human.id == human.id %>>
              <%= human.name %>
            </option>
          <% end %>
        </select>
      </label><br>

      <br>
      <input class="btn btn-primary" 
             type="submit" value="Update Dog!">
    </form>
    <br>
    <a href="/dogs">Back to Dog Index</a>
  </div>
</body>
</html>

app/views/dogs/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DOG APP</title>
  <!-- <link rel="stylesheet" href="/assets/stylesheets/bootstrap.css"> -->
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster|Pacifico|Cookie|Comfortaa|Ubuntu|Varela+Round">
  <!-- <link rel="stylesheet" type="text/css" href="/assets/stylesheets/application.css"> -->
  <%#= AssetPipeline.pipeline %>
  <%= AssetPipeline.read_manifest %>
  
</head>
<body>
  <div id="content"></div>
  <script type="text/babel" src="/assets/javascripts/main.jsx"></script>
  <div class="container">
    <div class="jumbotron">
      <h1>DOG APP</h1>
      <p><em>A comprehensive list of all dogs ever</em></p>
    </div>
    <ul>
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <li><%= message %></li>
        </div>
      <% end %>
    </ul>

    <h1>ALL THE DOGS</h1>

    <table>
      <tr>
        <th>Dog</th>
        <th></th>
        <th>Human Friend</th>

      </tr>
      <% @dogs.each do |dog|%>
        <tr>
          <td><%= dog.name %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= dog.human ? dog.human.name : 'None' %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><a href="<%= dogs_path(dog) %>">show</a></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><a href="<%= edit_dogs_path(dog) %>">edit</a></td>

        </tr>
      <% end %>
    </table>
    <br>
    <a style="text-decoration: none" 
       class="btn btn-success" 
       href="<%= new_dogs_path %>">
      Create a new dog!
    </a>
  </div>
</body>
</html>

app/views/dogs/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Dog | DOG APP</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster|Pacifico|Cookie|Comfortaa|Ubuntu|Varela+Round">
  <%= AssetPipeline.pipeline %>
</head>
<body>
  <div class="container">

    <ul>
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <%= message %><br>
        </div>
      <% end %>
    </ul>

    <h1>Create a New Dog</h1>
    <form action="/dogs" method="POST">
      <input type="hidden"
             name="authenticity_token"
             value="<%= form_authenticity_token %>">
      <label>Name<br>
        <input type="text" class="form-control" 
               name="dog[name]" value="<%= %>">
      </label><br>

      <label>Human Friend<br>
        <select name="dog[human_id]" class="form-control">
          <option value="0" selected="selected">None</option>
          <% @humans.each do |human|%>
            <option value="<%= human.id %>">
              <%= human.name %>
            </option>
          <% end %>
        </select>
      <br><br>
      <input class="btn btn-success"
             type="submit" value="Create a Dog!">
    </form>
    <br><br>
    <a href="/dogs">Back to Dog Index</a>
  </div>
</body>
</html>

app/views/dogs/partial.html.erb
<h1>THIS IS A PARTIAL</h1>

app/views/dogs/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DOG APP</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster|Pacifico|Cookie|Comfortaa|Ubuntu|Varela+Round">
  <%= AssetPipeline.pipeline %>
</head>
<body>
  <div class="container">
    <ul>
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <li><%= message %></li>
        </div>
      <% end %>
    </ul>

    <h1><%= @dog.name %></h1>
    <h3>House: 
      <% if @dog.human && @dog.house %>
      <a href="<%= houses_path(@dog.house) %>">
        <%= @dog.house.name %>
      </a>
      <% else %>
        <p>Stray :(</p>
      <% end %>
    </h3>
    <h3>Human Friend:
      <% if @dog.human %>
        <a href="<%= humans_path(@dog.human) %>">
          <%= @dog.human.name %>
        </a>
      <% else %>
        <p>None :(</p>
      <% end %>
    </h3>
    <br><br>
    <form action="/dogs/<%= @dog.id %>" method="POST">
      <input type="hidden"
             name="authenticity_token"
             value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <input class="btn btn-danger" type="submit" value="Delete <%= @dog.name %> :(">
    </form>
    <br>
    <p><a href="/dogs/<%= @dog.id %>/edit">Edit <%= @dog.name %></a></p> 
    
    <br>
    <a href="<%= dogs_path %>">Back to Dog Index</a>
  </div>
</body>
</html>

app/views/houses/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @house.name %> | DOG APP</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster|Pacifico|Cookie|Comfortaa|Ubuntu|Varela+Round">
  <%= AssetPipeline.pipeline %>
</head>
<body>
  <div class="container">
    <ul>
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <li><%= message %></li>
        </div>
      <% end %>
    </ul>

    <h1><%= @house.name %></h1>
    <h3>Inhabitants:</h3>
    <h4>Humans</h4>
      <ul>
        <% @house.humans.each do |human| %>
          <li><a href="<%= humans_path(human) %>"><%= human.name %></a></li>
        <% end %>
      </ul>
    <h4>Dogs</h4>
      <ul>
        <% @house.dogs.each do |dog| %>
          <li><a href="<%= dogs_path(dog) %>"><%= dog.name %></a></li>
        <% end %>
      </ul>
    <br>
    <!-- <form action="/dogs/<#%= @human.id %>" method="POST">
      <input type="hidden"
             name="authenticity_token"
             value="<#%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Delete <#%= @human.name %> :(">
    </form> -->
    <br>
    <!-- <p><a href="/dogs/<#%= @human.id %>/edit">Edit <#%= @human.name %></a></p>  -->
    
    <br>
    <a href="<%= dogs_path %>">Back to Dog Index</a>
  </div>
</body>
</html>

app/views/humans/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DOG APP</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster|Pacifico|Cookie|Comfortaa|Ubuntu|Varela+Round">
  <%= AssetPipeline.pipeline %>
</head>
<body>
  <div class="container">
    <ul>
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <li><%= message %></li>
        </div>
      <% end %>
    </ul>

    <h1><%= @human.name %></h1>
    <h3>Dog Friends:</h3>
    <ul>
      <% @human.dogs.each do |dog| %>
        <li><a href="<%= dogs_path(dog) %>"><%= dog.name %></a></li>
      <% end %>
    </ul>
    <br>
    <!-- <form action="/dogs/<#%= @human.id %>" method="POST">
      <input type="hidden"
             name="authenticity_token"
             value="<#%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Delete <#%= @human.name %> :(">
    </form> -->
    <br>
    <!-- <p><a href="/dogs/<#%= @human.id %>/edit">Edit <#%= @human.name %></a></p>  -->
    
    <br>
    <a href="<%= dogs_path %>">Back to Dog Index</a>
  </div>
</body>
</html>

app/views/layout/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DOG APP</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lobster|Pacifico|Cookie|Comfortaa|Ubuntu|Varela+Round">
  <%= AssetPipeline.pipeline %>
</head>
<body>
  <h1>SP SUP UPS UPS UPSUPSUPSUPSUPSUP SUP not UPS</h1>
  <%= yield %>
</body>
</html>